### ISSUE TITLE
Clear question

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1007]
**Currently** we have a "hidden" way to clear a question. You have to long press the question title and then you see a dialog:
![screenshot_20180209-171116](https://user-images.githubusercontent.com/923280/36037354-d66047a0-0dbc-11e8-88b7-7c5445772647.png)

If you press OK, the question answer will be cleared. 

**Issue 1**
There is no way to find out about this feature unless we tell the users or they discover by chance.
It would be better to have something like a clear button which will start to be visible once there is actual something to clear.

**Issue 2**
Single choice option questions have another hidden feature and is you can press an option itself to clear the question. This feature is also hidden. I would suggest to remove this and use the solution described in the issue 1 for all the questions.

**Comment by janagombitova** [comment]
What I think we need to answer is **Why would Alphonso use this feature, if he knew he had it?**. 

If the option question is mandatory, he must select an option. The the Clear feature would not bring him value. If the question is not mandatory, then he does not have to select an option in the first place. He would make value of the Clear feature only if the option question is not mandatory and he selected an option but does not want to have it selected anymore. Do you think this situation will happen? Is there another case when the Clear feature would be needed?

Currently he can clear all the answers put in using the Clear option in the form menu, that applies on all questions in the form. 

Just to add, we also have the same hidden Clear response window showing up for cascade questions. However, for cascades if you have selected an option from the dropdown and do not want to have it selected anymore, you can always "select" the Please select in the top of the dropdown. 

Because there is a way to "clear" the answers for cascades, how about fully removing the hidden Clear response window for cascade questions? Maybe in another issue?

**Comment by janagombitova** [comment]
Something relevant I just learned. More and more partners ask for the consent of the respondents. They add it as a question in Flow with two options: Yes and No. If the respondent answers No the expectation is that all following questions are skipped (even mandatory) and the submission can be made. Sometimes our partner asks for basic generic information before the consent question, thus they want to have those answers in the dataset. But because currently in Flow, you can only make a dependency per question, not an entire group and a question can only be dependent on one question, getting this done is cumbersome. 

However, our colleagues found a way around it. 

Geert, via the support group, 16:38: "basically you can do your dependencies as usual, but all questions that are not dependant should be made dependant to the consent question."

Annabelle, via the support group, 16:33: "What about a monitoring form for the questions after q10?

This story is not relevant for this issue nor for the mobile app, but Nikki's workaround is: 

Nikki, via Akvo support group, 01:44: "chiming in here - I do this very frequently with a survey in the region and have always followed the "make everything dependent on that question" rule. Although, if they are only interested in recording people who confirm I often include in test saying "No - TERMINATE THE INTERVIEW AND USE CLEAR FUNCTION TO REMOVE ALL ANSWERS" That usually works to" 

So before we reconsider the value of the `clear` functionality we should make sure we handle consent questions first.
