### ISSUE TITLE
Photo question redesign

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1075]
Found by Jana:
"I published and uploaded the data (again) and now I have 80 minutes left and started collecting more data. I created a new point and when capturing the 2nd photo I got the error that Flow cannot get the media and I tried again to take the photo and then the app crashed —> have tried this before successfully.
after the app crashed I tired again and all worked fine"
device id:jana
device: Android 4, Samsung

**Comment by janagombitova** [comment]
Hey found another weird thing - but no crash. 

I was entering data for the form in your test folder on UAT1 called Images (with 10 photo questions). All was going well but at one point after saving the photo a thumbnail did not show. I could submit the form without any problems. I checked the submission in Inspect data tab and all photos were submitted correctly. But when I check the History on the phone I do not see the images. Thus I restarted the app. Checked the submission again and all worked well. 

![screenshot_2018-04-11-15-09-44](https://user-images.githubusercontent.com/12456965/38618865-139ebb0c-3d9b-11e8-8fa2-814eac7cc412.png)

**Comment by valllllll2000** [comment]
Update:
Sometimes image loading may fail and the image cannot be displayed due to lack of memory but the image did get saved correctly. We need to display some kind of error in this case or how some default thumbnail, what should it be? 
Another error can happen when we try to download an image but that fails. In that case we have a way of retrying the download.

**Comment by janagombitova** [comment]
@valllllll2000 I would go with a default thumbnail. Can be generic and just a photo graphic.

If Aplhonso clicks to enlarge it, will he be able to see the actual captured photo or not? If not, then we should consider a view informing him that his photo is saved, no worries, but he is out of memory and thus cannot see it (in better words) 

@loicsans and @Kiarii If you have a moment can you share what you think?

**Comment by valllllll2000** [comment]
One of the issues is we get a lot of out of memory errors which can now be fixed by this issue:

**Comment by valllllll2000** [comment]
In general we use some placeholders to indicate the file is being loaded and/or were errored. Here are some proposals.
error:
![ic_error](https://user-images.githubusercontent.com/923280/40104336-55a4d1e2-58f0-11e8-8c55-d5a310fd591f.png)
loading:
![ic_sync](https://user-images.githubusercontent.com/923280/40104352-5e968408-58f0-11e8-916b-0b543c29c08e.png)
@Kiarii @janagombitova what do you think?

**Comment by janagombitova** [comment]
After talking with @valllllll2000 we decided to show the loading placeholder to show that the image is saved and the thumbnail of the image is loading. Once the loading is completed Alphonso will see the thumbnail of the image/video. 

We however have one more case where we need @Kiarii your insight. Aplhonso takes a photo. The photo is saved correctly, but because of memory issues the Flow app cannot display the thumbnail. So now we show nothing. How can we show Alphonso that his photo is saved correctly, but we cannot show you a small thumbnail, but you click on this placeholder you will see your photo?

**Comment by Kiarii** [comment]
having a look..

**Comment by valllllll2000** [comment]
@Kiarii 1) The geolocation is extracted form the image. If it is missing we use the device location (if available) to add the information to the exif tag of the image (here is more info on exif https://en.wikipedia.org/wiki/Exif). But the way we have it is a bit controversial see https://github.com/akvo/akvo-flow-mobile/issues/1001. 
2) In read only mode we cannot delete images. Until a form has been submitted user can only replace an existing image by taking another one. When an image question is mandatory there would be no need to deleting, just replace it by the new one. On the other hand, we may need to provide a a way to delete especially for the non mandatory questions, in case they change their mind about submitting a picture. Deletion in any case should always require confirmation. @janagombitova what do you think?

**Comment by Kiarii** [comment]
thanks @valllllll2000! my question regarding the location tag was, do we need to show it?

**Comment by janagombitova** [comment]
@Kiarii and @valllllll2000 we decided to show Alphonso that we capture the geolocation of each photo as it is a default setting and we want to be transparent to our users on what info we collect. Thus the little sentence was added under each photo. And that should not change. 

The location is used often by Salim to check where the photo was taken in light of the data point location as a quality check of the data set and the submission. 

If we should show the actual location - that is a good idea, but lets handle that in a separate issue.

**Comment by Kiarii** [comment]
Having considered the issue, I thought we could present the thumbnails as follows (first 2 screens the thumbnail renders, last 2 it doesnt):

<img width="1693" alt="screen shot 2018-05-24 at 11 00 26" src="https://user-images.githubusercontent.com/12692444/40472804-29ddc024-5f43-11e8-95fe-ab5917cf10e1.png">

**Comment by valllllll2000** [comment]
@Kiarii I think something is wrong, I do not see any icons. Which icons shall we show for error? On the other hand this design is very nice with the geolocation underneath and all nice and tidy, I think we should add it in the future release but in this issue I just need to show some error icon when the loading fails.

**Comment by janagombitova** [comment]
Hey both, indeed we are combining a few improvements into one. My proposal and attempt to clarify things below: 

**With this issue**
- add the loading icon you suggested Valeria when loading the photo thumbnail
- if loading of the thumbnail fails (after showing the loading icon), instead of showing nothing, show the grey rectangular placeholder with the text 'View photo'. If Alphonso clicks on it, he can see the photo

**Separate issues** 
- Change how the TAKE PHOTO button looks and behaves. When a photo is taken rename it to RETAKE PHOTO and change the design (we have a larger button improving issue, I believe) and realign the buttons and geolocation info. 
- Changes to how geolocation is displayed. I would leave it as it is currently, as Valeria you wanted to change the logic in another separate issue, right? So the visual changes can be handled and reconsidered then.

**Comment by Kiarii** [comment]
I think in the case of loading we can use three animated dots on the placeholder but when loading fails we do not necessarily need to show an error or failure; we can just show the 'view image' text

**Comment by Kiarii** [comment]
following button design suggestions made in https://github.com/akvo/akvo-flow-mobile/issues/1103 I have refactored the above screens to match:

Location data loading & display
<img width="847" alt="screen shot 2018-06-07 at 17 08 44" src="https://user-images.githubusercontent.com/12692444/41105103-940f5272-6a75-11e8-8b32-0cbfb8a0b8c6.png">

Location data n/a & no thumbnail preview
<img width="848" alt="screen shot 2018-06-07 at 17 09 20" src="https://user-images.githubusercontent.com/12692444/41105131-a022d8fe-6a75-11e8-8865-85c8ae0cfe35.png">
