### ISSUE TITLE
Viewing videos UI improvement

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1076]
# Context 

Users can capture videos with Flow. It does not happen often, from the user research we know that it barely never happens, but it is possible. Once you capture a video you see a little thumbnail of the video. By clicking on it the video expands to full screen an starts to play. 

If Alphonso syncs in data from another device with videos, he can download the video and see it on his device. 

![screenshot_2018-04-11-14-51-50](https://user-images.githubusercontent.com/12456965/38617826-4980bf3e-3d98-11e8-9bb0-d02ca2e7165f.png)

# Opportunity

When Alphonso sees the video thumbnail he has no way to know if that is a photo or a video. He has to click on it to expand and then see the video playing. If a video and photos were captured it is hard to see the difference between the two (see image above). 

Would it be possible to add a play icon overlaying the thumbnail (as you have in the Gallery app) to visually show that this is a video and you can play to view it? What do you think?

**Comment by valllllll2000** [comment]
We could definitely add a play icon (different from the one for download). There is also another possibility: For now we display the video outside of the app. We could also have a small video view within the app so can just view the video without exiting the form. What do you think @janagombitova

**Comment by janagombitova** [comment]
What would be the benefits of that change?

**Comment by valllllll2000** [comment]
Advantages: 
* video is inside the form, more integrated with our app
* it makes more sense since we have the images that way (same behavior as images)
* we do not leave the app when viewing videos
* we do not depend on frameworks video player
* I do not need to share the file with Android framework (more security)

Drawbacks:
* More work for me developing that part (not too hard though)
* I have to handle play/pause/stop (related to the one above)

**Comment by janagombitova** [comment]
Sounds like a good change to make in my opinion from your Pros and Cons list above. 👍
