### ISSUE TITLE
Old devices and apk updates

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1093]
After version 2.4.8, devices with android < 4.0.3 will no longer be able to update.

**Consequences:**
* If android version < 4.0.3 we stop checking for updates
*  We need a way to inform the user he has an old version of the app and app can no longer be updated. Also we can suggest to update the device to a more recent android version (it is sometimes possible)

**Alternatives:**
* Display a message in about screen with the text:
Your device runs an old android version and the Flow app can no longer be updated. We recommend updating to a more recent Android 4.0.3 to continue using Akvo Flow.
* We have a task that checks for apks every 24 hours, we will not check apks for old devices but we can use it to display a notification instead saying the same message above.
* Do both (I would recommend this option).

**Comment by janagombitova** [comment]
I agree with both. 

So Aplhonso needs to understand that: 
- he cannot update Flow anymore, 
- he is missing out on data security improvements that can better protect the data he collects, 
- he cannot update because we do not support such old devices anymore - that our min version of Android is 4.0.3
- he can use Flow as he has, but better to upgrade to a more recent Android version. 

I think the message also needs to be visual so he sees that there is something off.

**Comment by janagombitova** [comment]
@Kiarii with the May release we will change what the minim version of Android we support (from 2.3. to 4.0.3). This means that users (1% of all our devices) that have Flow installed on an old device will no longer be able to update their Flow app version, missing out on the GDPR changes. They will be able to still use Flow. 

Valeria suggested above to inform them in two ways about this situation. Can you take a look?

**Comment by Kiarii** [comment]
I think these are some good suggestions

**Comment by janagombitova** [comment]
With Valeria and Kiarii we agreed on indeed adding this update to both places. Besides in the About page we will create a dialogue with the text (same as in About) and an image of a dinosaur to enlighten to message. 

Copy: You can no longer update your Flow app and enjoy our latest improvements. This is because your device runs an Android version older than 4.0.3. 

In the About page we will disable/remove the option to update the app version

**Comment by valllllll2000** [comment]
Here is how it looks now:
![screenshot_20180420-173758](https://user-images.githubusercontent.com/923280/39060529-e89aef38-44c1-11e8-8e5d-8dc1718f8eee.png)
![screenshot_20180420-143808](https://user-images.githubusercontent.com/923280/39060530-e8b4fc7a-44c1-11e8-8a44-fdf018d4f8da.png)

**Comment by valllllll2000** [comment]
one doubt, how often do we show the dino dialog? For the apk update we show every 7 days maximum. We will have the option to never show again so maybe every 24h is ok?

**Comment by janagombitova** [comment]
24h is definitely ok

**Comment by janagombitova** [comment]
@valllllll2000 besides aligning the text in the About page to the center all seems good. I just spoke with @loicsans who said we nailed it with the dinosaur, so Yay. We are good to go.
