### ISSUE TITLE
Take photo/video or select an existing one from your gallery

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1136]
# Context 

Currently when Alphonso reaches a photo or video question he must capture a new photo/video. I can imagine this rule is in place to make sure he actually takes a photo when in the field, on the spot. 

But sometimes he wants to select an existing photo that he already has on his device. 

For example today, we heard from a partner who asked if it is possible to select a photo from the gallery, because the phone used for Flow has a bad camera and they want a photo taken from a better device to be part of the answer. 

Or with MEA Burkina Faso the enumerators did not submit the with the monitoring and registration forms correctly. They had some registrations without monitoring. So they had to fill in the monitoring forms but were no longer in the field. So, they called the field to get the additional information. but they also had to take pictures, but could not and the field staff could also not send it to them to add to the submission.

# Opportunity
Allow Aplhonso to either take a photo/video, or to choose an existing one from his gallery on his device.

**Comment by valllllll2000** [comment]
Given we have the following issue to redesign the take photo view https://github.com/akvo/akvo-flow-mobile/issues/1075, how can we integrate the possibility to chose where to get the photo from: camera or device gallery. 
Alternatives:
1) Have a "get photo" button instead of the current "take photo" and then show a dialog to chose either "camera" or "gallery"
2) Inside the view instead of having 1 button have 2 of them: "take photo" "get from gallery"

The texts can be modified of course.

**Comment by Kiarii** [comment]
I have a few observations following up on the issue of supporting the ability to add images from the camera or gallery; I feel that if we add this option we sort of solve one problem and introduce another i.e. if we dont approach the issue both from the dashboard and the app
* Shd this be approached from the survey side so that the admin can choose whether an img is accepted from one only or both - given that there might be situations that only a camera img can be attached.
* If we do it only on the app, how much cognitive work are we adding for the user; in the process of figuring out from where was an img added) comparing form submission metadata e.g. time and image metadata e.g. time it was taken 
* or do we want to further add a metadata to specify the source, and in this case how do we liase with the dashboard data view; at least we ought to do this in the app so that Alphonso knows from which source he has added an image

else we might have a number of design options how we could support this including the 2 suggestions by Valeria; I have been doodling :)
![whatsapp image 2018-08-09 at 15 51 11](https://user-images.githubusercontent.com/12692444/43900423-8a9e8880-9bed-11e8-9b1f-d580f9c0cacc.jpeg)

**Comment by valllllll2000** [comment]
thanks @Kiarii for the designs, so I think they can work well except the action button. Bear in mind that this is a survey with many questions and can be scrolled, action button is for one action and in this case would be complicated to implement. I do like the 2 side by side for simplicity and 1 step less for the user.
As for the procedence, I do not think it matters. The truth is even if the picture is from the gallery most likely it was taken by this device at some point. Inside the image there are some metadata encoded with data and camera model, backend can extract those. @janagombitova do you think knowing where the picture came from can be useful? Shall we give the one who creates the survey a choice to limit the procedence or not?

**Comment by janagombitova** [comment]
I also like the 2 side by side, it is simple and clear and you have all in one sight. 

On your question if we should allow the survey creator to limit where the photo comes from, I to be honest do not know. But I do think we will learn from our users once this possibility is out, if they want more limitations or not. I can imagine it may improve the quality of the data if you can enforce that the photo has to be taken on spot, but that is just a guess. We can always first release these changes to the app and then learn about the limitations. So I would say let's create an issue and park it for now. 

On the meta data photos have I do think we can make more use of them. The 1st thing is how we take the photo location, that you mentioned @valllllll2000 that can be improved. If we show the location data for the encoded metadata, can we also show then it was captured? If yes, this should also be handled in a separate issue.

**Comment by valllllll2000** [comment]
## Test plan
Create a survey with a video and photo question. Make sure you can submit adding video and photo from gallery and from camera. Once submitted make sure the files and synced correctly with dashboard using inspect data tab

**Comment by janagombitova** [comment]
Works perfectly! This is a great addition to the app 👍 Lets see if we get feedback on restricting on the form level where the photos and videos should come from in the next months
