### ISSUE TITLE
Display image coordinates on a map

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1508]
We will now display coordinates underneath an image for photo questions, when available.

@stellanl  suggested to make these coordinates clickable to display them on a map with an intent.

The idea: when user clicks on the coordinates he is taken to google maps app displaying these coordinates. Clicking the link would take us to the google maps app so user will have access to all the its features.

Alternatives: 
* display within out app map with the location, similar we do with datapoints
* display a small map underneath the image with the location of the image

**Comment by janagombitova** [comment]
Interesting idea. My question would be: **Why?**. What is the value of showing the geotag on the map? I can picture that it is more informative to see the location of the photo on a map rather than just via coordinates to confirm the location is correct. In that case I would suggest we approach this issue and this one https://github.com/akvo/akvo-flow-mobile/issues/1284 in the same way.

**Comment by muloem** [comment]
@stellanl what exactly was the driver behind wanting to have this?  I have moved it to the backlog for now until we have some more time to closely review the user stories behind it.
