### ISSUE TITLE
Visually indicate datapoints were downloaded recently

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1592]
When new datapoints are assigned and downloaded by the app, we need to indicate to the user which ones are new in the app list of datapoints.

**Comment by valllllll2000** [comment]
Here is a screenshot with an example of UI
![Screenshot_1582821776](https://user-images.githubusercontent.com/923280/75465257-a82a7300-5988-11ea-87b5-48f21dbcfdc7.png)

**Comment by Kiarii** [comment]
i think this should be done as a notification - e.g. "Survey name: x forms and x datapoints downloaded" such as we do with forms - for a number of reasons
- New datapoints are not just in the list but also on the map (so showing the new label on the list would require a way to show new on the map)
- There is the potential for confusion in saying *new* since datapoints are created in the device; from the dashboard the device are assigned datapoints, so the terminology need to reflect that reality
- using the new label for each new datapoint, increases visual noise; to differentiate newly downloaded from already downloaded, we could consider either a background highlight (which would require already existing to have the same white bg) or use a bold font weight (which would require that we use normal weight) for already downloaded ones. Of course the question remains: when should that indication of "new be removed" is it after user sees them or actually opens each individually?

Additionally, If we consider the idea of assignments in the app then we might in the future move towards notifications like "New assignment name: 1 form & x datapoints downloaded", or "Assignment name: x datapoints downloaded"

**Comment by valllllll2000** [comment]
@Kiarii I understand your point, I just wanted to give more feedback about the idea. We had discussed it with @muloem and arrived to the conclusion there should be an easy way for users to pick which datapoints have been added to distinguish them from the old datapoints. The reason for that is we will no longer delete any datapoints from the device, ie there is no way to un-assign datapoints unless the user actively presses a setting to delete all data. Since that change https://github.com/akvo/akvo-flow-mobile/issues/1590 we need a way for the user to distinguish new datapoints. The basic idea was:
* add a way for the user to quickly see which datapoints have been recently added
* once the user opens a datapoint, that datapoint is marked as viewed and no longer appears as new
* we only considered this change for the list, not the map.
* the idea is the simplify for the user: which datapoints are new and need me to work on them and which ones were already on the device so he knows looking at the list which ones since he may end up with lots of datapoints
Given this new information, do you think it makes sense to provide this feedback in a way you think makes sense? It is true that either background highlight or bold would require changes in the original implementation (stop highlighting the non new datapoints or stop using bold for datapoint title).
As for assignments we actually decided against assignments in the app for now.


Considering

**Comment by muloem** [comment]
> i think this should be done as a notification - e.g. "Survey name: x forms and x datapoints downloaded" such as we do with forms - for a number of reasons

I agree with that. It helps orient users to know what they have received. 👍 

> There is the potential for confusion in saying new since datapoints are created in the device; from the dashboard the device are assigned datapoints, so the terminology need to reflect that reality

I also agree with this thought.  I guess we should be very clear about what we mean so rather than saying they are new datapoints, we should think of them as "unopened".  Perhaps indeed it is better to use a bold font weight or background highlight of some sort to differentiate them

>  Of course the question remains: when should that indication of "new be removed" is it after user sees them or actually opens each individually?

I believe here we may actually have a partial solution to one other problem that we have been experiencing, i.e. a user fills in a monitoring form twice because they maybe failed to distinguish between datapoints.  If we highlight the ones that are unopened, then they visually identify what they have already worked on and what is still unopened.
 
> How should we do it? I can provide screenshots with both highlighted version and bold.

Yes please 

> Shall we also display new datapoints on the map or we leave the map out of it?

Lets start with the list for now.

**Comment by valllllll2000** [comment]
Here are the screenshots for the 2 possibilities in each case the items 2, 3, 4 are new 
1) Background highlight
![Screenshot_1583233732](https://user-images.githubusercontent.com/923280/75770837-0f5d7400-5d49-11ea-8bb9-068ddb92fd93.png)


2) Bold text
![Screenshot_1583234196](https://user-images.githubusercontent.com/923280/75770860-197f7280-5d49-11ea-9478-088c85114a98.png)

**Comment by valllllll2000** [comment]
<img src="https://user-images.githubusercontent.com/923280/75777762-d62c0080-5d56-11ea-86e8-57622c9b8593.png" width="200" />
<img src="https://user-images.githubusercontent.com/923280/75777764-d75d2d80-5d56-11ea-8a42-c4c7df16ca0d.png" width="200" />
<img src="https://user-images.githubusercontent.com/923280/75777764-d75d2d80-5d56-11ea-8a42-c4c7df16ca0d.png" width="200" />

**Comment by valllllll2000** [comment]
@muloem here is the new version as per your comments
![Screenshot_1583242071](https://user-images.githubusercontent.com/923280/75780231-4046a480-5d5b-11ea-879f-c1f814b49a5b.png)

**Comment by muloem** [comment]
@Kiarii what do you think?

**Comment by valllllll2000** [comment]
> > i think this should be done as a notification - e.g. "Survey name: x forms and x datapoints downloaded" such as we do with forms - for a number of reasons
> 
> I agree with that. It helps orient users to know what they have received. 

The thing is we already show a snackbar with how many datapoints are downloaded:

<img src="https://user-images.githubusercontent.com/923280/75809078-72223000-5d88-11ea-8da7-1c79ea0f70ca.png" width="200" />

I think a notification makes sense when the user is not in the app but since the user presses the download menu option, in my opinion the Snackbar makes more sense but if you guys think a notification format makes more sense I can of course replace the SnackBar by the notification.
Another thing about forms: they are downloaded in a separate service from the datapoints, if we wanted to show both form number and datapoints we would need to make changes in the logic. For now here how it works:
User opens the app -> forms are downloaded without further interaction from the user
User presses download inside a selected survey -> we download the datapoints

**Comment by Kiarii** [comment]
#2 bold text would be way to do it; it creates minimal visual clutter 

btw had there been a special reason to use different backgrounds for the list items? I think a white background for all datapoints or if need with dividers for list items would make list items visually clean; I am referring here also to list items under Forms and History tabs.. but may be this is an different issue for another day

**Comment by Kiarii** [comment]
> Another thing about forms: they are downloaded in a separate service from the datapoints, if we wanted to show both form number and datapoints we would need to make changes in the logic. 
> For now here how it works:
> User opens the app -> forms are downloaded without further interaction from the user
> *User presses download inside a selected survey -> we download the datapoints*


It is awkward that the Alphonso has to download datapoints manually; it requires that he knows that some datapoints are due to be downloaded; in which case they have to manually do what ideally should be done automatically by the app (it is akin to having to manually 'download' messages in an email app, instead of the app doing so automatically). 

I understand this is the logic that we've of course, but with the direction that we are taking, an assignment (forms + datapoints) should be bundled together when it comes to downloading.. Even more so because we are moving away from those 'huge datapoints list download' which were inefficient and took too long (which made a case for separating forms and datapoints) to dealing with a subset of datapoints per device..

**Comment by valllllll2000** [comment]
#### Summary
Use bold font for newly downloaded datapoints
Once user opens them, they are no longer new
Other UI/logic changes will be handled in separate issues see #1593 and #1594

**Comment by valllllll2000** [comment]
## Test plan
Add some datapoints to a survey with monitoring enabled
Make sure they are synced (green)
Go to dashboard and assign these datapoints to your device
Go to app settings from the navigation drawer and press "delete collected data and images"
You will see datapoints disappear
Press download
The assigned datapoints will be downloaded, their text will be bold
Open one of them then go back
The opened datapoint no longer shows as bold

**Comment by Kiarii** [comment]
@valllllll2000 we can bold just the datapoint name, to make the text easier on the eye; sth like this
![image](https://user-images.githubusercontent.com/12692444/76201386-d9623900-61fb-11ea-89bb-5d97dd47e0cd.png)

**Comment by valllllll2000** [comment]
Here is a screenshot:
<img src="https://user-images.githubusercontent.com/923280/76320342-d725da80-62e0-11ea-88c1-ae384db69cdb.png" width="200" />

**Comment by valllllll2000** [comment]
And here a version without a background which will be removed one day.
<img src="https://user-images.githubusercontent.com/923280/76320724-5ca98a80-62e1-11ea-9c1b-8739cb468cb5.png" width="200" />
