### ISSUE TITLE
Data point list styling: date

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1604]
### Background
Currently we display the datapoint modified date: "Last modified x minutes/hours/weeks ago", see:

<img src="https://user-images.githubusercontent.com/923280/75770860-197f7280-5d49-11ea-9478-088c85114a98.png" width="200" />

@Kiarii's proposal:

> I would also like to propose an improvement on how we show the modified time; atm we are presenting as a primary element of the list and repeating the “Last modified:” for each datapoint which i think does not add extra value.. I think just showing the day is enough and it also enables us to get rid of the “ago” which we are atm also repeating for each list item.. what are your thoughts

Here is a screenshot of how it could look like:
![image](https://user-images.githubusercontent.com/923280/76219130-a167ef80-6215-11ea-8e39-0f6e8bd8d0ca.png)

### Questions and Thoughts
Position the date on the right, in my opinion is a very good idea.

As for the formatting, if it's today will we show **today** or **Mar 9**? Wouldn't it still be useful to show more details for today, ie **10 minutes ago** or **a second ago**? How would it benefit the user, less information?

**Comment by Kiarii** [comment]
@valllllll2000 these are some valid questions, 

I think we could for changes made today use time (with 24hr notation) e.g. 10:12, 18:27, or so.. and then change to dates e.g. Mar 9, once the last modified time is yesterday and so on.. 

This way, i think we can keep the timestamp short and also exact; e.g. instead of **10 mins ago**, we say **10:02**. I also think with the **10:02** Alphonso can precisely tell when a modification was made to a datapoint - which i think is the idea..

**Comment by valllllll2000** [comment]
![Screenshot_1586342581](https://user-images.githubusercontent.com/923280/78775444-831d1d00-7996-11ea-8f7f-f7f060afd1da.png)

**Comment by janagombitova** [comment]
It is a great change in terms of making the screen cleaner. But I have two comments/issues with it: 

* Consistency - in the designs we have two ways of showing the order of days and months and this can be confusing. As we use the 24h format which is commonly used in combination with the order DD-MM-YYYY we should use the order consistently so: 16 Mar, 26 Dec 2018. 
* Looking information - What about data points created the same day in the past. How will I know the difference and do I need to know? So how will I know which data point was modified earlier in the case of: one would be 19 Mar 2018 - 13:45 and another 19 Mar 2018 - 17:56
9:18? Do I need to know this difference?

**Comment by janagombitova** [comment]
To be able to push out the change of design but not loose information we give to users we can keep the change of date layout and format but standardise it to (also what Lumen is using): 
* 14 Jan 2020 - 10:45
* 19 Mar 2019 - 18:36
etc 

and then see if we can simplify it more with another iteration

**Comment by valllllll2000** [comment]
@janagombitova I have just realized maybe it would be best to let the formatting be according to the language. Here is an example side by side of I use the default for US English and French
<img src="https://user-images.githubusercontent.com/923280/79234874-2d031a80-7e6b-11ea-88e7-490e60ffc965.png" width="200" /> <img src="https://user-images.githubusercontent.com/923280/79234875-2d9bb100-7e6b-11ea-9475-9ebf31fceda8.png" width="200" />
What do you think?

**Comment by janagombitova** [comment]
I think that is very smart!

**Comment by valllllll2000** [comment]
@janagombitova After using the app I have noticed that we put the date next to the datapoint name (top right), and sometimes that name is very long:

<img src="https://user-images.githubusercontent.com/923280/79440785-b2570e00-7fd6-11ea-87ee-947d310c4fb7.png" width="200" />

I wonder if it wouldn't make more sense to put the date at the right/bottom or right middle, see below:
<img src="https://user-images.githubusercontent.com/923280/79440921-e0d4e900-7fd6-11ea-80a4-8d51310f51f0.png" width="200" />  
<img src="https://user-images.githubusercontent.com/923280/79440925-e16d7f80-7fd6-11ea-8bb0-ca1b6eb417d8.png" width="200" />

**Comment by janagombitova** [comment]
The middle looks best to me. Good catch

**Comment by janagombitova** [comment]
![IMG_1792](https://user-images.githubusercontent.com/12456965/83656131-7811f200-a5bf-11ea-9c18-713d202fc372.jpg)
I am reopening this issue as I think we need to reconsider the design once more. We made the change using a short data point name. But in practice the names are long (consisting of more answers). The changes now result in a lot of white space and less data points visible in the screen as one takes up a lot of vertical space. 

@Kiarii and @valllllll2000 what do you think?

**Comment by valllllll2000** [comment]
That does not look nice at all, I would in this case suggest putting the date at the bottom on the same level as status which is usually short, see for example:
<img src="https://user-images.githubusercontent.com/923280/79440925-e16d7f80-7fd6-11ea-8bb0-ca1b6eb417d8.png" width="200" />

**Comment by janagombitova** [comment]
Putting the date down is also a way to go, but then I wonder why not keep it in line with the rest... 

Do we have three different font sizes? Maybe we can make the ID, status and date the same size - small and decrease the font of the name too. How about also limiting the spacing a bit between lines to save space? 

And third thought, I know we spoke about it before and said we should keep the time stamp, so you know which point came sooner. But after looking at some other apps, I think we could remove it for older points (from yesterday onwards). What do you think?

**Comment by Kiarii** [comment]
- We cannot support arbitrarily long DP display names on the datapoint list screen. Else we end up with datapoint names spanning more than two lines. These have to be truncated at some point. I would suggest we settle for two lines - truncating the rest and showing DP display name in full in the DP profile screen, wherein we could even consider providing a location stamp when location/gps info is available for a DP
![image](https://user-images.githubusercontent.com/12692444/83730047-329e0500-a651-11ea-8887-30d59e908b83.png)

- DP profile screen sketch
![image](https://user-images.githubusercontent.com/12692444/83729455-4eed7200-a650-11ea-9251-9433c198e7e8.png)

- We are also over using and even duplicating  (in DP Form and  History tabs) DP data and time stamps. On the DP list screen, we do not need to use the two. We should use one or the other on the DP list screen but not the two - it sort of defeats the purpose..
![image](https://user-images.githubusercontent.com/12692444/83730247-77c23700-a651-11ea-8a4e-7e2435ede509.png)

- To take more space for the DP name, we can reduce the size of the DP status icon. Which calls into question why we are layering two icons as one while in the History tab we ditch duplicity.
- We should also consider the necessity of showing DP id on the DP list screen - does Alphonso actually refer to DP Id (using a print out or some other way) when in the field? - Would it suffice to show this on the DP profile screen? 
- We should also aim to ditch the duplication of DP status info - atm we use both text and icons, we should aim to use one; to reduce the amt of content on the screen while making it scannable and easy on the eye..

**Comment by janagombitova** [comment]
That is one long list of suggestions :) I made a summary of straightforward changes and then a list of what we still need to discuss clarify. I suggest we have a meeting with the three of us to talk them through. 

## Changes 
* [ ] Turnicate DP name if longer than 2 lines 
* [ ] Show time stamp for DPs created/updated today and show only date for the rest 
* [ ] Reduce size of DP status icon 
* [ ] Simplify DP status icon - @Kiarii are you suggesting to use what we use in the History view? So a green tick for Uploaded, orange disk icon for saved, and for submitted the wifi or the clock (in the transmission history there is different arrow like icon that we use and call queued, by the way) 
* [ ] Do not show DP ID in the list (if we move to the DP screen) - I think this is worth the experiment and to see if we hear back from users that they miss seeing this value in the list 

## To discuss: 
* Show DP display name in full in the DP profile screen - How will this work for non-monitoring DP where once you click on the point you see the submission? 
* Show DP location stamp in DP screen when location/gps info is available for a DP. Should this be clickable to view on the map? 
* Moving the status icon to the left.

**Comment by janagombitova** [comment]
Decisions: 
* On DP IDs - we will take the risk and hide it. We do not know if people use it so we will see if they do based on their reaction to the change. 
* With search, we need to reveal the ID when searching and hide when Al is not searching
* Moving the DP ID to the "data point screen" will be handled in a separate issue as we need to detail out where to show it (a `data point profile`) for monitoring and non-monitoring data points. 
* DP icons, we move to the right, under the date. Keep the colours as today, Kiarii to provide new icons (draft, you submitted = it is saved on the device = it has not been sent to Flow yet but the app is trying to do so if there is a network, uploaded/downloaded = received by Flow) and we use them in the other lists (History, Transmission history) as well
* If you have DP location enabled (and you have the location available) we show the location of the DP in the list. We considered make it clickable, but that would be hard and would mean to make the list longer what we do not want. We will see how to add the location to the `data point profile`. For now we leave the DP location (`distance`) as it is today
<img width="671" alt="5ab17000-8e92-4847-a639-1d64b04ee463" src="https://user-images.githubusercontent.com/12456965/84365538-e3684f00-abd1-11ea-9e33-57049760e09e.png">

**Comment by valllllll2000** [comment]
Here is how it could look:
![Screenshot_1591957958](https://user-images.githubusercontent.com/923280/84493908-dec29a00-aca8-11ea-8041-cc45713e559c.png)

**Comment by Kiarii** [comment]
already the list is noticeably cleaner :) small observation: 

- '.' instead of '/' in the date stamp, it makes it more legible. 
- with the distance we could also lessen the amt of info we provide. In place of "Distance: 3.893.14 km" we could just say "3.9 km" ("0.5km", "0.1 km") - assuming that it is self explanatory to Alphonso what the distance stamp means; with his every move, the distances update.  
- In addition it might not be necessary to be precise down to a cm.. However if we want to provide some precision in terms of meters, we could for distances below a km say "900 m", "5 m", "1 m"

**Comment by Kiarii** [comment]
After some deliberation and experimenting with icons for the datapoint states, I am tentative concluding that..

- There is a difference between an action and a state - perhaps not as noticeable - but from my experiments - attempting to use an into-cloud and into-device icons for uploading/downloading is a no, no as these imply an action more than a state.. Draft is perhaps unique in this case; the pencil icon can imply both status: draft and action: edit - which I think is practical for our case
![image](https://user-images.githubusercontent.com/12692444/84867389-c1644600-b083-11ea-81b6-4e06da0246bb.png)
   
- A “submitted” datapoint is in a state of either waiting to sync or syncing - for which I find a time icon or spinner being more indicative of the status (a background / server action) even respectively.. Atm when downloading Datapoints we do not indicate “downloading” but if we were to do that then a spinner would work both ways; downloading/uploading, and a timer in case of pending a connection, when downloading terminates in case of a connection outage.. I have come to assume that the time and spinner icons are more meaningful than a check icon - which typically indicates that content in question has been uploaded to the server (and is waiting to be pushed to a receiving device) while in our case it is not.
- For synced, lets keep the (single) check icon, and proceed from there.. I am reluctant to use a double check icon since that is typical of indicating state-workflow that differs with ours  
- This would mean that for the 3 states that we have - draft, (submitted i.e.) pending sync and synced, we can represent them as illustrated - which is an incremental improvement and not an overhaul change. We keep the check and timer icons more or less as they were used.. 
![image](https://user-images.githubusercontent.com/12692444/84867882-81519300-b084-11ea-85ec-8b4ad85b0b8f.png)
- It also means that since the 3 states and respective icons are distinct from each other, we do not need to re-code them (redundantly) by color..

**Comment by janagombitova** [comment]
@Kiarii just one question: Why not use the `spinner` for the submitted state then? It indicates the 'progress' of uploading (if happening or not due to connection, but Flow keeps on trying). Plus as an extra plus point for the `spinner`, looking at the screens it is hard to see at first glance the difference from the circular time and circular tick.

**Comment by valllllll2000** [comment]
> @Kiarii just one question: Why not use the `spinner` for the submitted state then? It indicates the 'progress' of uploading (if happening or not due to connection, but Flow keeps on trying). Plus as an extra plus point for the `spinner`, looking at the screens it is hard to see at first glance the difference from the circular time and circular tick.

I like the "time" icon for "pending" state because we don't know if it will be uploaded or not or when. The spinner really means something is happening now and it may be not the case. We do show "uploading" notification when datapoints are being uploaded. But I do agree the icons are too much a alike at first I though we only had 2 states. Maybe the tick should not have a circle in it?

**Comment by janagombitova** [comment]
@valllllll2000 ok then. Let's use the time. And a prototype with 2 options sounds perfect 👍

**Comment by valllllll2000** [comment]
<img src="https://user-images.githubusercontent.com/923280/84918184-92b89080-b0c0-11ea-87a9-db50f5e0dce5.png" width="200" />   <img src="https://user-images.githubusercontent.com/923280/84918189-93512700-b0c0-11ea-9745-b8995daf6c4c.png" width="200" />

**Comment by janagombitova** [comment]
I like the 1st colourful one. But curious to hear @Kiarii 's thoughts

**Comment by valllllll2000** [comment]
New example taking into account Kiarii's recommendations
![Screenshot_1592475947](https://user-images.githubusercontent.com/923280/85009681-23de4480-b15f-11ea-86c8-0c6c40123aaa.png)

* use 18dp images
* 54% opacity black outline icons from https://material.io/resources/icons
* align icon at the bottom right

**Comment by janagombitova** [comment]
It is looking promising. My only note is that we agreed **not** to move to black-n-white icons to not implement too many changes and to not loose the "quickly scan to see the status of my submissions" feeling the colours provide.

**Comment by valllllll2000** [comment]
Here is an example of colored icons (with 54% opacity)
![Screenshot_1592553501](https://user-images.githubusercontent.com/923280/85110647-82fd9100-b213-11ea-9875-c7e923e7b218.png)

**Comment by valllllll2000** [comment]
and full opacity color
![Screenshot_1592553981](https://user-images.githubusercontent.com/923280/85111397-92310e80-b214-11ea-8867-279543640a60.png)

**Comment by valllllll2000** [comment]
> the date stamp should take a smaller font size - since it is an element of a secondary or tertiary importance in the datapoint component - when it is of the same size as the datapoint, it competes for prominence with the name which is the primary element.. (this is also the case with apps such as messaging and chat apps)

**Comment by Kiarii** [comment]
All datapoints are equal but some are more equal than others; the inequalities
- Some datapoint names may only span one line
- Some datapoints may not have a distance stamp

In which case, the alignment of datapoint elements appear as being visually unbalanced;
![image](https://user-images.githubusercontent.com/12692444/85111742-6cf4ce00-b21d-11ea-93b6-e46ea5d157f5.png)

Given this inequalities, keeping the status icon on the left makes more sense, since the elements of a datapoint are located in visually balanced manner e.g.

![image](https://user-images.githubusercontent.com/12692444/85112107-cf4dce80-b21d-11ea-9ebf-9326680bf99b.png)

About the color coding, am still reluctant to keep it given that :
- green for synced makes most sense, even though it is a redundant coding - the check by itself indicates that everything is right or done for a dp
- orange if it implies a warning or sth that the user needs to do shdnt apply to the clock icon - as syncing is a device/app task.
- the icons are distinctive by themselves in which a double coding by color adds another layer of cognitive effort to discern not one but two codes..

**Comment by janagombitova** [comment]
@Kiarii I hear your concerns about the colour coding, but I am going to use my power of veto this time and say, we keep the colours. We are changing enough already in the screen. If this change is taken positively and users get used to it, then we can again reopen the discussion on taking away the colours for the icons.

**Comment by valllllll2000** [comment]
Latest screenshot with the requested changes
<img src="https://user-images.githubusercontent.com/923280/85155298-de05a700-b258-11ea-8feb-d6de274c1c55.png" width="300" />

**Comment by Kiarii** [comment]
Notes for more improvement:
- For the check icon lets try a green: 00AB34
- Align the status icon to middle of the first line of the dp name. The size of the icons, i will comment after test driving the emerging visual hierarchy..
- The distance and time stamps are secondary to the datapoint name. If the dp name is 16px, lets see how the component looks as a whole with distance as 14 and time as 12. 
- datapoint name and accompanying metadata stamps take black (000000) as the font color with alphas of 87 and 54% respectively

**Comment by valllllll2000** [comment]
> Notes for more improvement:
> 
> * For the check icon lets try a green: 00AB34
Done
> * Align the status icon to middle of the first line of the dp name. The size of the icons, i will comment after test driving the emerging visual hierarchy..
OK
> * The distance and time stamps are secondary to the datapoint name. If the dp name is 16px, lets see how the component looks as a whole with distance as 14 and time as 12.
Done, we used sp instead of pixels so its 16sp, 14sp and 12sp
> * Dp name line height: 24, dist stamp line height: 20
I don't understand what this refers to, maybe a screenshot could help, does it mean the height of the textview?
> * datapoint name and accompanying metadata stamps take black (000000) as the font color with alphas of 87 and 54% respectively
What is those metadata stamps? 
For now what I did is datapoint name text color #DE000000 (the first 2 refer to alpha)
and distance and time #8A000000 not sure it's what you meant

**Comment by Kiarii** [comment]
- with the alpha I meant opacity of 87 and 54%
- Line height dictates the space between lines in a paragraph (more or less) https://material.io/design/typography/understanding-typography.html#readability. We need to experiment to find a suitable visual balance..

<img width="1062" alt="Screenshot 2020-06-22 at 10 55 50" src="https://user-images.githubusercontent.com/12692444/85263100-5d70c180-b477-11ea-9cca-d2a35390f049.png">

**Comment by valllllll2000** [comment]
![Screenshot_1592833222](https://user-images.githubusercontent.com/923280/85294313-c3bd0a80-b49e-11ea-97db-45ddf7d24b47.png)

**Comment by valllllll2000** [comment]
New version after Kiarii's recommendation:
![Screenshot_1592897741](https://user-images.githubusercontent.com/923280/85374372-f9acce00-b534-11ea-9595-96040b0b2bc3.png)

**Comment by valllllll2000** [comment]
There seems to be a visual defect in some cases where location is missing:
![Screenshot_20200717-174252](https://user-images.githubusercontent.com/923280/87805352-75a8e600-c855-11ea-9491-37729a607a3d.png)

1) The space is empty when the distance is missing, there should be only one line in this case
2) For some reason only 1 of the 2 points is displayed, reloading the app corrects the issue
