### ISSUE TITLE
Datapoint profile view

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1661]

**Comment by Kiarii** [comment]
(i've renamed the issue :))

**Why do we create this issue**
We need to organize a datapoint's information - what makes up its profile - so that it is viewable in a meaningful way - for both monitoring and non-monitoring assignments. 

A datapoint profile **can** consist of:
- Datapoint name / display name
- Date of creation
- Detail/about: information submitted in dp registration form (atm this is part of history)
- Location (if available) - distance from Alphonso's current location - incl. "show on map" or "navigate to datapoint" icon element
- Image [dreamingly for later] - will enhance datapoint identification for datapoints that have images as an identifying feature
- Forms (assigned monitoring tasks)

**Comment by Kiarii** [comment]
updates on the dp profile:
**Datapoint profile for non-monitoring survey**
![image](https://user-images.githubusercontent.com/12692444/85690271-17686780-b6dc-11ea-9f88-e75f5f3fc981.png)


Some rationales and thoughts:
- For monitoring surveys (see below) bring monitoring forms [tasks] into view straight away
- For non mon surveys, bring submitted data straight into view - remove the form selection and history pages which are unnecessary
- Introduce tabs as a way to switch between a) monitoring forms [Tasks] (see sketch below), b) dp profile and c) show on map
- The map tab should both show user's location (or the action to show this) and dp location and (later) shapes pertaining to that specific dp 
- list question groups so that its easier for users to jump straight to a question group of interest. Having used tabs for the 3 main sections of the dp means the question groups cannot be tabbed since that would introduce a double tabs next to each other which would be confusing 

**Datapoint profile for monitoring survey; 2 monitoring forms**
![image](https://user-images.githubusercontent.com/12692444/85688944-e3d90d80-b6da-11ea-8c7c-95ca6963b125.png)

**Comment by janagombitova** [comment]
Before investing more time in this, let's discuss the changes in person

**Comment by janagombitova** [comment]
My gut tells me this issue might be linked to #1669
