### ISSUE TITLE
Remove map tab when no location is available

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#1662]

**Comment by Kiarii** [comment]
**Why do we create this issue**
To clear up the datapoint list screen by removing the map tab when datapoints in a survey contain no location or geoshape question - since there would be nothing to show on the map.

**what would it mean**
This would involve removing all map views - Map tab and handles e.g. View map in datapoint profile screen, as well as distance stamps - since there would be no information for these..

**Comment by valllllll2000** [comment]
From a technical point of view this is a bit tricky for the datapoint list as currently we display the datapoints without loading the form. We load the form once a datapoint was selected, so we would have to change that. Removing maps from datapoint profile is easier since we already know if the datapoint has location or not.
