### ISSUE TITLE
Provide proper user onboarding

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-flow-mobile#1749]
**Whats the deal?**
Upon a fresh installation, we should show a proper onboarding screen to communicate what can be done with the app. Atm we show a (new) "datapoint assignment" feature highlight which is not reflective or relevant for a fresh install onboarding.

![Screenshot_20201029-110241](https://user-images.githubusercontent.com/12692444/97542605-1de35480-19d8-11eb-8f0f-1c1f6cd7f136.png)

**What approaches might apply**
- A clear and concise onboarding screen(s) communicating the top features or actions users can do with the app
- Incl. a Next / Skip options landing the user to the 'account' creation
- it is also possible to bundle up the 'account creation components' with the onboarding enabling the user to jump to action without having to go via or skipping the onboarder e.g
<img width="205" alt="Screenshot 2020-10-29 at 12 44 40" src="https://user-images.githubusercontent.com/12692444/97551851-8c2e1400-19e4-11eb-89d5-a557f3965f30.png">

- A background illustration of what can be done with the app might also make the onboarder more precise if picture ever told a 1000 words;
<img width="369" alt="Screenshot 2020-10-29 at 12 42 29" src="https://user-images.githubusercontent.com/12692444/97552010-c7304780-19e4-11eb-92b7-d356718bd606.png">

- Account creation screen should provide more snippet as unto what "Username" and "Device id" are and why create them e.g. "create a username to collect data, to receive survey, or whatever.."
- Ideally, users will also expect sth about terms and policy - about account/data handling - but this we may postpone for now

**Comment by janagombitova** [comment]
I think this is a great idea! I, however, would like to keep it to focus on onboarding and leave the changes to the account creation to another issue (even if it is just to add an explanation as to what the two fields are). And yes, terms and conditions are for another day.

**Comment by janagombitova** [comment]
I was following https://material.io/design/communication/onboarding.html#usage to look at what content we need. Then I looked at out website to how we describe Flow https://akvo.org/flow-caddisfly-lumen/ and to all to ensure we use a consistent message: 

> Capture, clean and monitor reliable data anywhere, regardless of internet connection. Collect accurate, timely, geo-tagged information, images and data. Easily align and manage distributed teams through the online workspace.

> Monitor changes over time and scale your efforts up to international level. Create and export simple reports and visualisations

We highlight: 
* Scalability 
* Security 
* Multilingual 
* Able to collect data anywhere: Flow’s user friendly Android app and Caddisfly water quality testing app are designed to work in remote locations that are often off grid. Collect data even when you have no network coverage, and upload it automatically when coverage resumes or manually via USB.

# Top features or actions users can do with the app
* The main task is to submit a form 
* Autosave 
* Multilingual - the app but also forms 
* Monitoring - download existing data points and update with new information 
* Work offline - fully (form form download, maps download to pushing out submitted data) 

# Question
I just realised that when you first download the app and "login" you land on the data point list page. We assume a form is automatically downloaded to the app, but the user is not in a `form list` screen. So she actually needs to know she needs to open the top menu. A possibly related change: https://github.com/akvo/akvo-flow-mobile/issues/1754

But what about cases when there is no survey assigned and no form is automatically downloaded: https://github.com/akvo/akvo-flow-mobile/issues/1748

Instead of changing how we have things organised in the app - to keep the implementation to only handle the onboarding - so we need to somehow inform Al to go to the menu to select the form? 

# Next steps
* Define content and designs 
* Show onboarding to first-time users - after installing the app NOT after updating the app 
* Do we need translation? 
* How to handle the question above
