### ISSUE TITLE
Devices with special fonts show as ????? in dataset

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#1762]
**Describe the bug**
On WHH we received a question about why some data in the dataset is shown as `??????????`. This was for free text submissions. But also for `Device ID`. The WHH team then noticed that the 2 devices with this issue show in a special font in the Flow online workspace. 

<img width="1062" alt="Screen Shot 2021-01-07 at 14 50 44" src="https://user-images.githubusercontent.com/12456965/103900412-1044fc00-50f8-11eb-816c-5dbc04ab486d.png">
<img width="1059" alt="Screen Shot 2021-01-07 at 14 51 12" src="https://user-images.githubusercontent.com/12456965/103900414-10dd9280-50f8-11eb-99f8-35fce3257a64.png">

The questions are (might need to split into separate issues, but I am trying to add everything here so we have a base): 
* why do these two devices show differently in the Flow UI? we should show the device ID with the same standard font regardless if a special font is selected on the device (if this is the reason)
* why do the device IDs show as ????? in the dataset? can we prevent this from happening? 
* why do free text answers show as ????? in the dataset? can we prevent this from happening? 

**To Reproduce**
1. Go to 'welthungerhilfe.akvoflow.org'
2. Check the Devices tab and use the browser search option to find the 2 devices 
3. Dataset: Syria_Turkey_Lebanon>2020>SYR1078>SYR1078_Agricultural_HOH_Assessment_form has the issue on the dataset level 

**Support issue** 
https://akvoo.reamaze.com/admin/conversations/typo-in-akvo-flow-data

**Comment by valllllll2000** [comment]
I am really at loss here of why this happens. So far the first device name is 𝘩𝘢𝘵𝘦𝘮 but if I search 'hatem' in the datastore it is not found, you need to write it 𝘩𝘢𝘵𝘦𝘮

**Comment by valllllll2000** [comment]
I am still investigating what happened but I have looked at the data.json file and instead of the ??? here is the text:
𝗮𝗵𝗺𝗲𝗱 𝗱𝘆𝗮𝗯 𝗮𝗹𝗮𝗯𝗼𝗱

if I paste it into the IDE code it becomes:
String t = "\uD835\uDDEE\uD835\uDDF5\uD835\uDDFA\uD835\uDDF2\uD835\uDDF1 \uD835\uDDF1\uD835\uDE06\uD835\uDDEE\uD835\uDDEF \uD835\uDDEE\uD835\uDDF9\uD835\uDDEE\uD835\uDDEF\uD835\uDDFC\uD835\uDDF1";

but java code is able to read it correctly. In the datastore, I can find this string and it's all correct. 
so the dashboard is not able to display these characters but the data is all there and correct. When we export the sheet, the characters are encoded wrong but if I paste that word in the spreadsheet myself, it is displayed correctly

**Comment by valllllll2000** [comment]
After more research, I have come to this conclusion, for example the letter 'a' is represented:
https://www.fileformat.info/info/unicode/char/1d5ee/index.htm
so it's \uD835\uDDEE for the letter but if you remove \uD835 then the code does not work and the letter cannot be read

**Comment by valllllll2000** [comment]
this has been solved in akvo/akvo-flow#3716
