### ISSUE TITLE
Offline maps

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#238]
Research alternatives to Google Maps. We need to implement a mapping service that supports offline caching (unsupported by GMaps), most likely with Mapbox. This issue can be used to log any library/service to handle common things already integrated in FLOW: location management, clustering, polygon drawing, etc

**Comment by ichinaski** [comment]
# OSMdroid

[OSMdroid](https://github.com/osmdroid/osmdroid) is a (almost) full/free replacement for Android's MapView (v1 API) class. It also includes a modular tile provider system with support for numerous online and offline tile sources and overlay support with built-in overlays for plotting icons, tracking location, and drawing shapes.

A nice addition to this core library would be [osmbonuspack](https://code.google.com/p/osmbonuspack/), which includes some goodies like marker clustering.

# Mapbox

The [Mapbox Android SDK](https://github.com/mapbox/mapbox-android-sdk) is basically an osmdroid fork, with some significant differences:

* GeoJSON and TileJSON support added.
* The Mapbox Android SDK is Apache 2.0 licensed, and does not include any GPL or copyleft add-ons.
* Mapbox Android SDK is a small core design. OSMDroid's semi-related utilities like GPX uploading, UI zoom buttons, GEM & Zip file support, Scale Bar, Compass Overlay, and more have been removed. These requirements will be better served by separate modules that do one thing well.
* Interfaces and abstract classes are only defined when suitable: most single-use interfaces are removed for simplicity.
* Data objects like points and lines use doubles instead of the E6 int convention. This simplifies implementations. The reuse pattern is also deemphasized, since it's less necessary with newer JITs.
* Instead of supporting specific tile layers with hardcoded paths, Mapbox Android SDK provides an easy-to-configure TileLayer class.
* Small modules are used in place of local implementations - DiskLRUCache for caching, OkHttp for connection niceties, and android-geojson for GeoJSON parsing.
* Markers can optionally use the Mapbox marker API for customized images.
* Code style follows the Sun conventions
* Automated tests are included.
* slf4j dependency is removed

Still, Mapbox for Android (unlike the iOS counterpart) does **not** have clustering support. There seems to be some ongoing discussions around this topic (https://github.com/mapbox/mapbox-android-sdk/issues/538), but the clustering integration is not implemented yet. It looks like the project did have some clustering integration in the past, but due to some (performance?) issues, it was fully removed (https://github.com/mapbox/mapbox-android-sdk/issues/303)

**Comment by ichinaski** [comment]
Some feedback from first itereation:

Aulia
-----

* Satellite layer
* Aulia expected the question response (feature collection) to be present in the Map tab.
* Manual geoloc input?
* Center map at start
* Feature info (point number, area, perimeter, etc)?

Anna-Marthe
-----------

* Disable manual input? (force GPS readings)
* Dragging points can be tricky if not accurate enough while selecting a point.
* On rotation, map clears -- FIXME
* Back soft icon (FLOW logo) not ready yet -- FIXME

Joy
---

* Accuracy indicator. An enumerator might need to know when to delete and recapture a point.
* <3 points in an area should not be allowed -- this is tricky as we should allow users to save a partial response and resume it later on
* Stats

**Comment by valllllll2000** [comment]
Update on mapbox in 2018
* Clustering is now possible https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/MarkerClustersPluginActivity.java
* Offline browsing is possible https://www.mapbox.com/android-docs/map-sdk/overview/offline/

Problem: library is only available with minSdkVersion 15, but we need 10. See if possible to use an older version of the lib.
Further tests need to be done if we can use it for displaying datapoints and/or drawing geoshapes

**Comment by valllllll2000** [comment]
**Update: Mapbox requires api 15, minimum. Api 10 i not supported.** 
Mapforge and osmdroid are still the only possibilties BUT with above mentioned limitations.

**Comment by janagombitova** [comment]
@valllllll2000 I just spoke with Kiarii and shared with him the prototype you made. He will take a look at the UX and how we can go about adding this great value to Flow. I am typed down some notes here for him and us to give some more context. 

# Opportunity - Offline maps

With this initiative we will like to make it possible to allow users to download a map to their phone to be able to use it offline and thus ensure full offline data collection.

## Offline data collection currently
In the office (or at home) Alphonso syncs in the forms he needs to complete, checks he has the correct form version. If he is going to monitor data, he also syncs in data points and finishes the preparation to go to the field. Even though in many countries internet is accessible, many of our users capture data in remote places offline. 

For capturing data offline Flow provides all the functionality needed, but if Alphonso wants to see on the map where he is located and where his points are located, he has a blank screen with indicated points as there is no connection to load the map tiles. Furthermore, if he needs to capture a geoshape he can do so, but on a blank map. Thus he has no visual that any info location related is correct. 

## Have maps offline 

We want to enable Alphonso to see a map when collecting data offline. He should be able to save specific tiles of the area where he will be going to and these should be visible for him when using Flow offline. 

## To keep in mind 
- Aplhonso user needs to be connected to the internet to be able to save a map to use later offline 
- he needs to be able to select a particular map - he might be covering more than one location
- phone storage is always a concern as we want to ensure he has enough space on his phone to capture data, thus he needs to understand that saving a map will take up of this space
- he needs a way to remove a map - maybe he will no longer go to the location or simply to free up space 
- if possible it would be nice if Alphonso can choose what map type he wants

## Stop supporting old devices 
On Monday I spoke with Akvo's MT who gave us the go ahead on stop supporting old Android devices as the devices connected to Flow's instances with the Android version between 2.3 and 4.0.2 and active in 2017 and 2018 represent only 1% of all devices. Thus we can start working on the full change to Mapbox.  

# To do and questions 
- We need to handle communication on stop supporting old devices and release once all affected users are well informed about the consequences of the change
- For old devices what happens if they hit to update the app? 
- Do we want to add some walkthrough screens to share info about the improvements with updating the app?

**Comment by janagombitova** [comment]
@valllllll2000 Today we started with @Kiarii user testing the latest version of the mock ups. You can find the notes from the calls here:https://docs.google.com/spreadsheets/d/1fy17w62H5ab1Ajc5lxboTpFXZpRxHCAAlBPUh21ZvrY/edit#gid=1927027248

Once done, lets talk more on what we learned and how to take it further.

**Comment by janagombitova** [comment]
With @Kiarii we held 4 user interviews where we checked the usability and value of the prototype. After each call we made adjustments to the designs and validated them in the next call. All the notes from the research can be found here: https://docs.google.com/spreadsheets/d/1fy17w62H5ab1Ajc5lxboTpFXZpRxHCAAlBPUh21ZvrY/edit#gid=1927027248

Below are the final mock ups (and @Kiarii will provide more detailed ones for the implementation) and a summary of what we learned in the user research. 

# Insights from user research 
- users do go to remote areas currently, to see points on the map they learn how to cache the map, thus this new feature would be of great help
- creating the offline map will most likely be done by Salim when setting up the phones for data collection and he will then tell Alphonso how to select the offline map he needs
- using the word 'pin' was confusing so we switched to simpler 'select' and 'deselect' that was proven to be directly understandable 
- the workflow on creating the maps and using them was clear
- having a offline maps icon at all offline maps actions helped to keep the user understand that she is working with offline maps in different screens 
- having enough storage on the devices for the data is important - Salim needs to know how much size the map will take to decide how big of a map he will download
- ideally Salim will go for one big map, but if storage wise does not support that, then he would download multiple smaller maps to cover the areas Alphonso will go to and then Alphonso can swith accordingly 

# Implementation 

With @valllllll2000 and @Kiarii we then walked through these insights and agreed on what will go to the 1st implementation and what can wait for later. 

Here is the last version of the mock ups: https://invis.io/3NJO0ZHSQ8Y

We also agreed on the following details: 
- the offline maps action buttons, and the entire feature, will be available to Alphonso at all times, also when working online. We decided to take this route, rather then showing the offline maps select maps button only when offline, because Alphonso may be in the field on mobile data but the costs are too high to load a map, or he is on unstable data and loading of the map may take too much time, making it easier just to use an offline map. 
- we will change the word "update" to **"redownload"** as it is more understandable - means redownloading the offline map you have created a while ago to make sure it has all the updated parts of the map 
- selecting a different map tile (satellite, terrain, roads, etc) depends on what is available via the map SDK and Valeria will take a look at that in the 2nd implementation round, it also might have affects on where we place the offline map select icon in the screen, as we will then have: new data point FAB; offline map select, choose map tile (available for online maps) icons in the map screen 

@valllllll2000 will take care of the separate implementation issues. 
@Kiarii will provide the detailed screen designs as we go and will also provide the final icon to be used to represent the offline map.

**Comment by Kiarii** [comment]
In conjunction with the idea of combining map modes (online, offline) and map selections I have made some revisions to the mockups as the workflow changes somewhat. Here is the revised version https://projects.invisionapp.com/share/YTKEEOVQPFM - I will make future updates and improvements here..
