### ISSUE TITLE
Minor Issue - Add more logical ordering on response error screen

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow-mobile#355]
At the moment the ordering of the question list seems to be a bit arbitrary when there's a couple of questions which have problems:

![screen shot 2015-10-19 at 11 54 54](https://cloud.githubusercontent.com/assets/3003031/10576017/4963b664-7658-11e5-83a8-8557c4c23a75.png)

Perhaps ordering by question number would be more intuitive?

**Comment by janagombitova** [comment]
Closing this issue as the ordering of questions is based on their order in the question group and the other of the groups themselves. The UI is not very intuitive because we show only the questions out of the question group context. We can look at the design later again, so adding this issue to the opportunity backlog for now.
