### ISSUE TITLE
Mandatory validation issue

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#411]
In the app when I have mandatory questions, select the answer and deselect it, then the form still gets submitted.  

The workflow is: 
I have a mandatory option question with multiple options enabled. I select one option, then fill in another answer to the following question. I deselect the option and I click on submit. Expected behaviour is that the app does not enable the submission because the mandatory question is missing an answer but it actually submits the form. 

We did not test it with option questions where multiple is not allowed.

**Comment by ichinaski** [comment]
Thanks for the detailed description. Will look into this.

**Comment by ichinaski** [comment]
**Test plan**:

> The workflow is:
I have a mandatory option question with multiple options enabled. I select one option, then fill in another answer to the following question. I deselect the option and I click on submit. Expected behaviour is that the app does not enable the submission because the mandatory question is missing an answer but it actually submits the form.

**Comment by rumca** [comment]
If the test plan is:

* Set up form with mandatory option question, multi enabled
* Select option
* Fill out following question
* Deselect option
* Try to submit

That no longer works, validation is applied as expected :+1:
