### ISSUE TITLE
Prevent fake or mocked up GPS data

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#424]
# Overview

We have partners seriously affected by corruption. They want to use FLOW to PROVE that something was measured, monitored, etc properly. When using GeoQuestions and image geotagging, we need to ensure the GPS-provided data is real and accurate.

While the new 1 minute-timeout approach defined recently will help us collect accurate data from the GPS, we have no restrictions on *mocked up locations*. That is, locations explicitly set in an app like *Fake GPS*, which will override the system-provided ones.

My suggestion is to disallow these apps if the manual editing is disabled in the question definition.

**Comment by muloem** [comment]
@ichinaski this will move to the next milestone right?

**Comment by ichinaski** [comment]
@muloem Yes, good point!

**Comment by ichinaski** [comment]
@muloem thinking of merging the GeoQuestion and geo-tagging location listeners as discussed in the previous release, so the mocked up locations check gets only defined in one place. What do you think?

**Comment by muloem** [comment]
What we could do is only restrict the mocked location check to the geo tagging (if thats possible)  for now so that we give it at least one release cycle to have the location listener get some "field testing". and if nothing major shows up then we can migrate the geolocation to that a release later. i.e. 2.2.6.  Thinking more from a prudent perspective.

**Comment by ichinaski** [comment]
Sounds good :+1:

**Comment by ichinaski** [comment]
Implemented on #439
