### ISSUE TITLE
Ensure cascade questions are complete

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#425]
Cascade question's validity check acts up in some circumstances, making it possible to submit a partial or void response.

**Comment by ichinaski** [comment]
**Test plan:**

* Download form 59999115 from UAT
* Ensure:
    * Mandatory cascades cannot be left blank
    * Mandatory cascades cannot contain partial responses
    * Non mandatory cascades cannot contain partial responses
    * Non mandatory responses can be left blank

**Comment by rumca** [comment]
test plans pass as described :+1:

**Comment by akvotender** [comment]
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/cascade-resources
Assignee: Geert Soet

Message:
Please cc frederic@akvo.org in the response and contact him if you need more info.

This is an urgent request, data collection is going on.
https://m3p-eva-rdc.akvoflow.org/admin/

We are using many survey, many different cascades and sometimes 2 cascades in 1 survey (we had the bug that cascade didn't work in the repeat group, so the partner doesn't really trust our system anymore ...)

In the extract sent by the partner, we can see that for the same cascade, the number of levels varies from one line to the other. It is like the cascade would not have the same number of level depending on the form...

The partners wants the extract of the cascade used for each survey. And we need to understand why the number of levels is inconsistent in one question ...

Hope that is clear .... otherwise let me know... again, Frederic is looking into it, but has not found the problem yet...
Cheers
Emeline

----- Forwarded Message -----
From: "crocker" &lt;crocker@hydroconseil.com&gt;
To: "frederic" &lt;frederic@akvo.org&gt;
Cc: "Emeline Bereziat" &lt;emeline@akvo.org&gt;
Sent: Tuesday, April 12, 2016 12:31:00 PM
Subject: Envoi d’un message : Copie de 16.04.06_V2A_1700922_envoi Fred

Pour notre discussion skype.
Audrey
