### ISSUE TITLE
Caddisfly questions don't work in repeated question groups

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow-mobile#462]
Due to a property (caddisfly test uuid) not being copied, the caddisfly question doesn't work in repeated question groups.

**Comment by janagombitova** [comment]
## Test plan

1. Create a survey with Caddisfly questions in it. Make sure that some of the questions are in a repeated question group.
1. Assign the survey to your device.
1. Open the form on your device and collect data and run the tests
1. Make sure you can run the tests for Caddisfly questions when in repeated group. Make from 1 - 7 repetitions across multiple submissions 
1. Submit the data and check on the dashboard that data was submitted as expected

**Comment by janagombitova** [comment]
duplicate https://github.com/akvo/akvo-flow-mobile/issues/475

**Comment by janagombitova** [comment]
Issue still relevant - not resolved

**Comment by janagombitova** [comment]
@nhternup and @valllllll2000 - I tested the latests Flow app version and the latest Caddisfly version Nischal you shared with me today and this issue seems to not exist anymore. See on UAT1 > 1.9.13 Folder > Jana regression round > 1.9.13 MF surveys (jana) > 1.9.13 Monitoring survey > Registration form > data point submitted by "Jana Caddisfly" 

 I want to put more effort into testing this and making sure it is truly not a problem, but I was wondering - did any of you make changes that resolved the problem?

**Comment by valllllll2000** [comment]
@janagombitova I myself have not done any changes related to this. Copying the entire caddisfly file might have solved the issue, but I am not 100% sure.

**Comment by nhternup** [comment]
@janagombitova - I've not made any changes towards fixing this issue.

**Comment by janagombitova** [comment]
Interesting. @valllllll2000 and @nhternup thank you for the clarification. I will run a few more tests to be sure this is not an issue anymore and update the issue accordingly.

**Comment by janagombitova** [comment]
Tested this issue once again and can confirm all is working now. Users can run the tests even if they are located in a repeated group, answers show properly on the device, dashboard and in reports. Will close this issue for now.
