### ISSUE TITLE
Design changes after update of support library

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#559]
After support library update (issue #489), @janagombitova has found multiple issues with the new design, detailed in this issue https://github.com/akvo/akvo-flow-mobile/issues/508

**Comment by valllllll2000** [comment]
> It is a good improvement, 
Thank you @Kiarii 
>A couple of points that could be refined further:

>1. the settings options look disabled - the list header ought to have a darker shade than their descriptions (https://material.google.com/components/lists.html#lists-usage)
I can easily change that, putting a darker shade (for example `#000000`) for the titles and leave th description same.
>2. the dropdown (picker) could use an 'underline' else it also qualifies as a signifier for an expandable-collapsible element (https://material.google.com/patterns/errors.html#errors-user-input-errors)
Sorry but I do not understand which part you refer to. The link you provided is for error messages in edittexts but there are none in the example screenshot. Maybe could you provide the text of the example to know which element you refer to.
>n. any specific reason the questions are coded twice: with bold and italic? (https://material.google.com/components/text-fields.html#text-fields-style)
So maybe having the questions in bold is enough, I can remove the italic, I do not know why they are coded this way.
>@loicsans maybe you can look into the color usage even if not for this iteration..

**Comment by Kiarii** [comment]
@valllllll2000 thanks for the feedback.

1. shd works as you suggest.

2. a dropdown contains an "underline" in both default and selected state - the COUFFO & LALO shd have that; let me know if it makes sense (i ref the error page caz it contains an illustration for that..)
<img width="244" alt="screen shot 2016-12-12 at 16 45 52" src="https://cloud.githubusercontent.com/assets/12692444/21103378/d90b1d48-c08a-11e6-89a4-19611efa5156.png">
<img width="774" alt="screen shot 2016-12-12 at 16 46 39" src="https://cloud.githubusercontent.com/assets/12692444/21103386/e5834f6e-c08a-11e6-974e-59c306b940c9.png">

3. this was more of a question, maybe Jana knows the reason there was double coding there. If no specific reason, we shouldn't use either..

**Comment by janagombitova** [comment]
@valllllll2000 and @Kiarii 

1) I agree with bringing the settings titles back to black and could that also be applied on the list of data points? they also seem disabled due to the font colour (now grey originally black) and the same refers to the list of forms in a monitored survey where there must be a colour difference between the enabled forms (registration for a new point, monitoring for an existing point) and the disabled forms (monitoring forms for a new point and registration form for an existing point)

2) Indeed bringing back the underline would bring a better visible indication. Also in the menu we are missing a line between the different actions. 

3) The bold questions are not mandatory and the bold and italic are for mandatory questions. But as we already indicate is something is mandatory with asterix, we can remove the double coding and have all questions only bold.

**Comment by valllllll2000** [comment]
Test plan:
1. List of datapoints: make sure text is enabled and black color
2. Settings screen: text must be black
3. List of forms in monitored survey: color difference between enabled and disabled ones
4. Questions should all have black text color, be enabled and the mandatory questions should be bold and with * (no italic)
5. Underline in cascade
6. Check if hamburguer menu works and has the right design
7. Alert dialogs: they should have the material design with buttons colored in blue.
Alert dialogs can be found in: menu option -> stats, settings -> about, scan barcode (if no barcode scanner), in settings all admin tasks

**Comment by janagombitova** [comment]
👍  everything looks great!
