### ISSUE TITLE
Survey bootstrap should be triggered automatically if possible

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#635]
Check if we can track changes in the filesystem to avoid having to restart the app when a survey is pushed to the device.

**Comment by valllllll2000** [comment]
seems to be possible https://developer.android.com/reference/android/os/FileObserver.html

**Comment by valllllll2000** [comment]
And unfortunately FileObserver has a bug in Android 6.0 https://issuetracker.google.com/issues/37065227

**Comment by valllllll2000** [comment]
## Test plan
* Create a bootstrap file
* Connect device to PC via usb
* Put it in the folder akvoflow/inbox
* After a maximum of 30s, you should see a notification "Done loading data from SD Card" which means bootstrap has been processed.
* Test especially on Android 6 devices as for them I had to add a workaround. These devices will take a bit longer to get the notification (up to 30 seconds). Also they have to be still plugged via USB until the notification appears or it will not work. 
* Should also work on all other devices.

**Comment by janagombitova** [comment]
Hi @valllllll2000 I followed your test plan and here is what I found: 
- if I have the app off while connected to the PC and putting the file in the folder, nothing happens and I have to close the app and open it to trigger the reading from the SD card (the same behaviour as we had before) 
- if I have the all closed while moving the file and then open the app I do get the notification right away. 

Is this the excepted behaviour?

**Comment by valllllll2000** [comment]
@janagombitova it seems that it does not work as expected:
1) What do you mean by having the app off? You mean the screen of the device is off?
2) Which device are you using?
3) What happens if you have the app displayed while moving the files to the device?

**Comment by janagombitova** [comment]
1. What do you mean by having the app off? You mean the screen of the device is off?

I have the app off from running on the background on the phone. So I have the screen on the device's home page. 

2. Which device are you using?

My Samsung - Android 4.4.2

3. What happens if you have the app displayed while moving the files to the device?

Nothing. I waited for two minutes. After the 1st minuted I unplugged the cable from my PC and then waited for one more minute, but nothing changed on the app. So then I closed it and opened the app again and that is when I got the notification.

**Comment by janagombitova** [comment]
works as expected
