### ISSUE TITLE
Improve Reloading all surveys and Downloading form

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#660]
After looking at the text of the dialogues shown when running the two actions we need to improve them to follow the standard patterns, in a simple way present the message coming across and use simple words. 

# Reload all surveys 

Current description: Deletes and re-downloads assigned surveys (only run if instructed)

**1st dialogue:** 

Title: Authorisation required 
Text: Please enter the administrator passcode: 
Actions: Cancel, OK 

**2nd dialogue after inputting the correct passcode:**
 
Title: Please Confirm
Text: Are you sure you want to purge and re-download surveys? 
Actions: Cancel, OK 

# Download Form 
Current description: Downloads arbitrary surveys (only run if instructed) 

**Dialogue:** 
Title: Authorisation required 
Text: Please enter the administrator passcode: 
Actions: Cancel, OK 

Some background information on [dialogues](https://material.io/guidelines/components/dialogs.html#dialogs-alerts)

**Comment by janagombitova** [comment]
Here are some initial thoughts: 
- what to do with descriptions? do we need them (also in relation to the possible location change of the actions)
- name change: 
   - reload all surveys to **Reload all forms**
   - download form to **Download specific form** 
- **Reload all forms** 
   - what are the risks around this action? I am asking so we know what tone to use in the dialogues 
   - 1st dialogue (remains the same - I have no ideas on this one right now)
      - Title: Authorisation required
      - Text: Please enter the administrator passcode:
      - Actions: Cancel, OK
   - 2nd dialogue after inputting the correct passcode:
      - no title only the question: Reload all forms? 
      - Actions: Cancel, Reload 
- **Download Form** - no ideas for improvement at this moment 

@valllllll2000 @Kiarii and @loicsans what are your thoughts?

**Comment by valllllll2000** [comment]
@janagombitova for now the logic of "reload all forms" is the following:
- get a list of the current survey ids
- delete these surveys from device database
- get surveys from server using the ids we got in step 1, so only those surveys will be updated
- insert new surveys in device database

I would suggest to modify the logic:
- get ALL surveys/forms available for this device same as what happens when we start the app
- delete all surveys
- insert newly gotten surveys
This new method: 
+ allows us to get even the newly assigned survey instead of the user having to restart the app if a new survey is assigned
+ only delete after we successfully get the new surveys from the server, that way if there is a connection problem, we do not delete the existing surveys 

If we switch to the new method, I think the scary dialog will not be necessary as we do not delete collected data, only surveys and only if we get them from server successfully. One doubt though: if some surveys got deleted, their data may still be on the device, not sure what will happen in that case.

**Comment by janagombitova** [comment]
@valllllll2000 that sounds like an interesting idea. I can cross check what currently happens with data for surveys that get deleted if the data is in saved state and in exported state. Will share findings here

**Comment by janagombitova** [comment]
connecting these two issues as I feel they are linked https://github.com/akvo/akvo-product-design/issues/222

**Comment by janagombitova** [comment]
@valllllll2000 so I did some little experiments with the current app and here is what I found" 

## if a form is downloaded to the device via inputting the form ID 
- submission is saved - remains on the device 
- submission is exported  - remains on the device 

## if a form is downloaded via assignment 
- submission is saved - remains on the device 
- submission is exported - remains on the device 

## If a form is on the phone via an assignment, but no longer part of the assignment at the point of Reloading all surveys 
- submission is saved - remains on the device 
- submission is exported - remains on the device 

## If a form is on the phone via an assignment, but no longer part of the assignment and fully deleted from Flow at the point of Reloading all surveys 
- submission is saved - no longer visible to Alphonso
- submission is exported - no longer visible to Alhonso

For this last case I found an interesting thing. If I had the app opened on the form, that I then deleted from Flow and then Reloaded all surveys, the form did not show again in my list, but if I just closed the menu I was still seeing my deleted form and points. If I wanted to click on a data point (or on the plus icon) I got a toast saying `Form not found. Please re-download all forms`. What is a confusing message as the form does not exist anymore and I have just redownloaded all my forms.

![screenshot_2017-03-24-16-11-52](https://cloud.githubusercontent.com/assets/12456965/24300465/d244c4e2-10ac-11e7-8637-0c2cd8f592ca.png)

Not sure if we need a separate issue for this and how to handle it. It is good that the app does not let Alphonso interact with the form at all anymore, but the message is confusing and ideally nothing for this form should be showing anymore.

**Comment by janagombitova** [comment]
Please see this comment: https://github.com/akvo/akvo-flow-mobile/issues/636#issuecomment-290720491 I personally agree, that we should reconsider the value of having Reload all surveys. We want to make it as easy as possible for the users to get the forms (or new form versions) on their phone. 

I think we need to consider removing Reload all surveys and replacing it with a simple Reload all forms that will trigger downloading the assigned survey forms to the device. The risky things we need to consider is what to do with cases when a form is not part of an assignment for the device but on the phone already because: 
- was downloaded to the phone via inputting the form ID
- was downloaded to the phone via bootstrap
- was part of the assignment, but then removed from the assignment 
- was part of the assignment, but then removed from the assignment and fully deleted from the dashboard 

@Kiarii and @valllllll2000 and @muloem What are your thoughts?

**Comment by valllllll2000** [comment]
First, I see 2 options here as to what "reload forms" should do:
Option 1: Use the form ids already present on device and only reload those
Option 2: Get all the forms available for this device id and eventually (?) delete all forms that are not assigned
The issue here is of course the bootstrapped and manually downloaded forms. I think in the long term we should consider that even if you use bootstrap the files you should still assign the form to a device? I think this is even out of the scope of this issue but:
1) Should we only allow "assigned forms": say you can download a form by id but you can only view it -> read only form, maybe we could separate "read only" forms from "write" forms?
2) Shall we request making assignments to devices before the forms can be bootstrapped? Or if a file was bootstrapped should we consider this device automatically assigned (would there even be a way to do this?).

**Comment by janagombitova** [comment]
I agree that the bootstrap topic is out of scope, but you are making some good points here.

Regarding the Reload forms topic the user need we should solve is that currently our users to get in new versions of forms or extra forms assigned to their phones they force close and reopen the app and this in not an ideal way to use it. Would it be possible to as you suggest in Option 2, to get all forms available for this device ID (updated versions or new forms) but not delete the ones that are on the phone but "should not be"?

To be honest I am not sure how to deal with these forms... 

If we do not delete forms with this action, can we then take away the need to input the passcode, as we are not risking anything?

**Comment by valllllll2000** [comment]
After talking to @janagombitova we have decided that the "reload forms" feature will work the same way as reopening the app: just reload all forms for the device. The second tab will allow downloading one form and will require a password, working the same way the entry in settings currently works. Both download all forms and one form will be removed from the settings screen.

**Comment by janagombitova** [comment]
Just to add on your comment @valllllll2000 the "reload forms" will not be passcode protected.

**Comment by janagombitova** [comment]
duplicate of #1180
