### ISSUE TITLE
After deleting everything, users and surveys, the previous survey title still shows

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#790]
**Steps to reproduce**
Have at least one survey and select it.
Go to settings / delete everything
Go back to survey, notice that:
The previous survey title is displayed
The + button is visible
The menu items are still there
The message says: you have no datapoints yet...

What should actually happen?
Should we take the user to the screen we add users? Same as when user just installed the app
Should there be a special error message saying you have no users, add one?

**Comment by janagombitova** [comment]
After out call with @valllllll2000 we agreed to bring the user to the user creation screen (initial one after installing the app)

**Comment by valllllll2000** [comment]
Note: the previous device id will not be deleted, it will be displayed as prefilled in the "login" screen

**Comment by valllllll2000** [comment]
## Test plan
After installing the app, and entering user and device details, go to settings and press "delete everything" once you see the delete confirmation Toast, press back and you should be taken to the login screen with the previous device id prefilled.

**Comment by janagombitova** [comment]
Tested this issue as it was in the 2.4.0.1 build on UAT1 and all the following workflows work perfectly: 
- delete everything, brings me back to the login screen with Device ID filled in and name to be added 
- changed ID, repeated above steps, all ok
- changed ID after deleting everything, also all ok

After the PR for this issue is reviewed, will test on old devices and then it can be good to go.

**Comment by janagombitova** [comment]
All looks good.

**Comment by janagombitova** [comment]
👍  works like a charm
