### ISSUE TITLE
Simplify Check SD Card State

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-mobile#803]
Check SD Card State is one of the many items in our Settings. 

*following description comes from @valllllll2000 and this issue https://github.com/akvo/akvo-flow-mobile/issues/501* 

For now this calculates device's available space and displays a dialog. Most devices now have a setting in device preferences which displays information about device internal storage (ACTION_INTERNAL_STORAGE_SETTINGS) so we could either redirect the user there or just display the value directly without the user have to press this setting. I would suggest move this inside about page in that case.

**Comment by valllllll2000** [comment]
@janagombitova I have given it a bit more thought and had another idea: we already check of device memory before filling a form but maybe the possibility to check for remaining memory should be inside the menu of the Form screen as it is directly useful there? Or always displayed somewhere on that screen. It definitely should not be in settings because there is nothing to set.

**Comment by janagombitova** [comment]
Today with @valllllll2000 we agreed to keep this item in the Settings but add it under the Configuration label and call it **Available storage** 

Once the user clicks on it, it opens Storage Setting in the phone

**Comment by janagombitova** [comment]
Works like a charm on newer devices and tablets. Will check with the old timer once able to install the app.
