### ISSUE TITLE
Settings to temporary publish data - UI

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-mobile#993]
Basic steps
- data is not published by default; user has to do it manually
- data is being published
- data is public, with a timer for depublishing it

![image](https://user-images.githubusercontent.com/12692444/35432283-3c9b3f9c-0288-11e8-8aa0-68fc681bdd10.png)

**Comment by Kiarii** [comment]
A small update: my self and Jana have agreed to change the 'Publish data' detail text as follows:

![0 1 c - settings _ gdpr on](https://user-images.githubusercontent.com/12692444/36786682-f60504d8-1c8f-11e8-93c2-f928a11ac91b.png)

**Comment by valllllll2000** [comment]
Here are some screenshots of how it looks
50867a02-2831-11e8-9905-d424ae0b4afa.png)
![screenshot_20180315-091018](https://user-images.githubusercontent.com/923280/37451249-504f8a60-2831-11e8-990f-a8e67ce69d80.png)

**Comment by janagombitova** [comment]
Only one tiny change needed here: Once user clicks on the Publish data options, can you change the text below to: 'Data is now available for bulk upload over the next'

This change is because from the user testing it was unclear to the participants what the timers with minutes means. Once we added the above sentence to the prototype, the following testers clearly understood that the file will only be available for 90 minutes, what many found a long enough time and a good decisions to keep the data private eventually. 

https://projects.invisionapp.com/share/ABG2CT39MPC#/screens/281738125

**Comment by valllllll2000** [comment]
## Test plan
Make sure the UI in stettings is as expected in the specs above

**Comment by janagombitova** [comment]
Works great and looks good too 👍
